project_id = "tvjrltlhpfieczbacfxe"
[functions.newsletter-subscribe]
enabled = true
verify_jwt = true
import_map = "./functions/newsletter-subscribe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/newsletter-subscribe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/newsletter-subscribe/*.html" ]

[functions.newsletter-unsubscribe]
enabled = true
verify_jwt = true
import_map = "./functions/newsletter-unsubscribe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/newsletter-unsubscribe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/newsletter-unsubscribe/*.html" ]

[functions.newsletter-analytics]
enabled = true
verify_jwt = true
import_map = "./functions/newsletter-analytics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/newsletter-analytics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/newsletter-analytics/*.html" ]
