// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvjrltlhpfieczbacfxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2anJsdGxocGZpZWN6YmFjZnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTY2MTUsImV4cCI6MjA3MjMzMjYxNX0.4xwujdKIeq2a1hZmrk5PAZU6urIP-WyeDuM7nkzzKK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});